version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install serverless -g
      - npm install 
  build:
    commands:
      - cd novavolt-energyusage
      - sls invoke test --stage qa -v
      - sls deploy --stage qa -v
#      - sls invoke test --live --stage qa -v
artifacts:
  files:
    - '**/*'
  base-directory: .serverless

