# name of the service
service: novavolt-energy-usage-${self:provider.stage}-${git:branch}

# variables section
custom:
  stage: ${opt:stage, self:provider.stage}
  branch: ${git:branch}


provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, env:AWS_STAGE, 'dev'}
  region: eu-central-1
  iamRoleStatements:
  -  Effect: "Allow"
     Action:
       - "s3:*"
     Resource: "*"
  -  Effect: "Allow"
     Action:
       - "sqs:*"
     Resource: "*"

# Lambda function
functions:
  getMsg:
    handler: handler.hello
    name: ${self:service}-hello
    events:
      - http: GET /
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "s3:ListBucket"
        Resource: !Ref novavoltEnergyUsageBucket
      - Effect: "Allow"
        Action:
          - "s3:PutObject"
        Resource: !Ref novavoltEnergyUsageBucket
      - Effect: "Allow"
        Action:
          - "sqs:*"
        Resource: !Ref novavoltEnergyUsageInQueue
      - Effect: "Allow"
        Action:
          - "sqs:*"
        Resource: !Ref novavoltEnergyUsageOutQueue

# use plugins (for example to having access to git values (like the branch))
plugins:
  - serverless-plugin-git-variables

# Resources section to specify other resources in CloudFormation style
resources:
  Resources:
    novavoltEnergyUsageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-bucket
    novavoltEnergyUsageInQueue:
      Type: AWS::SQS::Queue
      Properties: 
        QueueName: ${self:service}-incoming-queue
    novavoltEnergyUsageOutQueue:
      Type: AWS::SQS::Queue
      Properties: 
        QueueName: ${self:service}-outgoing-queue
