service: novavolt-energyUsage

custom:
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, env:AWS_STAGE, 'dev'}
  region: eu-central-1
  iamRoleStatements:
  -  Effect: "Allow"
     Action:
       - "s3:*"
     Resource: "*"

functions:
  getMsg:
    handler: handler.hello
    name: ${self:provider.stage}-${self:service}-hello
    events:
      - http: GET /
# you can add statements to the Lambda function's IAM Role here
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "s3:ListBucket"
        Resource: !Ref novavoltEnergyUsageBucket
      - Effect: "Allow"
        Action:
          - "s3:PutObject"
        Resource: !Ref novavoltEnergyUsageBucket

resources:
  Resources:
    novavoltEnergyUsageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: novavolt-energy-usage-bucket