'use strict';

// tests for getZapCloudData
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const assert = require("assert")
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('getZapCloudData', '/get-data-zapcloud.js', 'getData');

describe('getZapCloudData', () => {
  before((done) => {
    done();
  });

  it('getZapCloudData', () => {
    return wrapped.run({}).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
  
  it('getZapCloudData == 200', () => {
    return wrapped.run({}).then((response) => {
      assert.equal(200,response.statusCode);
    });
  });
});
